### PR TITLE
changes for chemical heating

### PR DESCRIPTION
**Pull request by fvitt**
This is for chemical heating associated with the dissociation of O2 and O3 in the upper atmosphere. 

This is a draft PR for now and should not be merged in without discussion.

### CODE REVIEW

**Comment by fvitt** [comment]
@mattldawson 

Rather than adopting the changes in this PR, I propose implementing a separate method the the photolysis_rates class for calculating the chemical potential energy which could be invoked something like
```
cpe(:) = obj%chemPotEnergy('ReactionName',...)
```

These parameters could be be set in the json configuration file for the reactions that contribute to chemical potential heating:
```
  real(r8), parameter :: wc_o2_a     = 175.05_r8   ! (nm)
  real(r8), parameter :: wc_o2_b     = 242.37_r8   ! (nm)
  real(r8), parameter :: wc_o3_a     = 310.32_r8   ! (nm)
  real(r8), parameter :: wc_o3_b     = 1179.87_r8  ! (nm)
```
See  https://github.com/fvitt/CAM/blob/e37cebbd4edc7a96b57a50e4d9332e84adba5b9d/src/chemistry/mozart/mo_tuvx.F90#L138

Calculations of the bond dissociation energies, as is done here
https://github.com/fvitt/CAM/blob/e37cebbd4edc7a96b57a50e4d9332e84adba5b9d/src/chemistry/mozart/mo_tuvx.F90#L485

could be done internal to the photolysis_rates, maybe at construction time.

Does this make sense?  Thoughts?

**Comment by mattldawson** [comment]
> @mattldawson
> 
> Rather than adopting the changes in this PR, I propose implementing a separate method the the photolysis_rates class for calculating the chemical potential energy which could be invoked something like
> 
> ```
> cpe(:) = obj%chemPotEnergy('ReactionName',...)
> ```
> 
> These parameters could be be set in the json configuration file for the reactions that contribute to chemical potential heating:
> 
> ```
>   real(r8), parameter :: wc_o2_a     = 175.05_r8   ! (nm)
>   real(r8), parameter :: wc_o2_b     = 242.37_r8   ! (nm)
>   real(r8), parameter :: wc_o3_a     = 310.32_r8   ! (nm)
>   real(r8), parameter :: wc_o3_b     = 1179.87_r8  ! (nm)
> ```
> 
> See https://github.com/fvitt/CAM/blob/e37cebbd4edc7a96b57a50e4d9332e84adba5b9d/src/chemistry/mozart/mo_tuvx.F90#L138
> 
> Calculations of the bond dissociation energies, as is done here https://github.com/fvitt/CAM/blob/e37cebbd4edc7a96b57a50e4d9332e84adba5b9d/src/chemistry/mozart/mo_tuvx.F90#L485
> 
> could be done internal to the photolysis_rates, maybe at construction time.
> 
> Does this make sense? Thoughts?

This sounds great to me! I'll go ahead and create an issue for this, and try to schedule it for next sprint.

**Comment by K20shores** [comment]
@mattldawson can this be closed now?

**Comment by mattldawson** [comment]
yes, this logic was included in #50

**Pull request closed without merging**
